# Generated by Django 3.0.5 on 2020-04-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200403_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_by',
        ),
    ]
