# Generated by Django 3.0.5 on 2020-04-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200403_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descript',
            new_name='body',
        ),
    ]
