# Generated by Django 3.0.5 on 2020-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200405_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
